import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import custom from '../styles/custom.module.css'
import { useState,useEffect} from 'react'
import React from 'react'
import axios from 'axios'
import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'reactstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import  router from 'next/router'
import Table from "react-bootstrap/Table";


export default function Home() {
  const [text, setText] = useState();
  const [record, setRecord] = useState({
    sr_no:null,
    plot_size:'',
    dealer_name:'',
  });
  const [modal, setModal] = React.useState(false);
  const toggle = () => setModal(!modal);
  const [errormodal, setErrorModal] = React.useState(false);
  const errortoggle = () => setErrorModal(!errormodal);
  const [dberrormodal, setDBErrorModal] = React.useState(false);
  const dberrortoggle = () => setDBErrorModal(!dberrormodal);
  const [file,setState]=useState('')
  const [data,setData]=useState([])
  
  useEffect(() => {
    
    // const config = {
    //   headers: {
    //     Authorization: 'Bearer ' + localStorage.getItem('token'),
    //   },
    // };
    axios
      .get(`https://api.mazglobal.co.uk/maz-api/verification`)
      .then(response => {
        setData(response.data.data);

      })
      .catch(err => console.log(err));
  }, []);

  const handleChange=(e)=>{
    setText(e.target.value)

  }
  const verifyFormNo=()=>{
    if(text==null || text=='')
    {
     errortoggle()
    }
    else{

    
   let status=false
    data.map(it=>{
      if(it.app_form_no==text)
      {
        setRecord(it)
        toggle()
        status=true
      }
    })
    if(status==false)
    dberrortoggle()

  }
}

const clear=()=>{
setText('')
toggle()
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Verification</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
<div className={custom.body}>
    <div className={custom.formBody}>

        <div className={custom.formItems}>
            <h3>File Verification System</h3>
            <p>Fill in File Form Number below.</p>
            <div className={custom.requiresValidation} novalidate>

                <div className={custom.formFiled}>
                    <input className={custom.formControl} type="text" 
                     value={text}
                     onChange={(e)=>handleChange(e)}
                     name="name"
                     placeholder="Enter Verification Form No" required/>
                </div>

                <div className={custom.formButton}>
                    <button id="submit" type="submit" onClick={verifyFormNo}
                    className={custom.btnPrimary}>
                      Verify</button>
                </div>
            </div>

        </div>

</div>
</div>

<Modal isOpen={modal} toggle={toggle}>
        <ModalHeader toggle={toggle}>
          <div style={{display:'flex',justifyContent:'center',width:'400px'}}>
            <img style={{width:'40px'}} src="/download.png"/>
            <p style={{marginTop:'20px',margin:'10px'}}>Verified</p>
            </div>
        </ModalHeader>
        <ModalBody>
        <Table  striped bordered hover>
                <thead>
                  <tr>
                    <th>SR No</th>
                    <th>Plot Size</th>
                    <th>Dealer Name</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    
                    <td>{record.sr_no}</td>
                    <td>{record.plot_size}</td>
                    <td>{record.dealer_name}</td>
                  </tr>
                 
                </tbody>
              </Table>
        </ModalBody>
        <ModalFooter>
          <Button color="primary" onClick={clear}>
            OK
          </Button>
        </ModalFooter>
      </Modal>
     
      <Modal isOpen={errormodal} toggle={errortoggle}>
        <ModalHeader toggle={errortoggle}>Alert</ModalHeader>
        <ModalBody>
          <>!Please Add Verification Form No</>
        </ModalBody>
        <ModalFooter>
          <Button color="primary" onClick={errortoggle}>
            OK
          </Button>
        </ModalFooter>
      </Modal>

      <Modal isOpen={dberrormodal} toggle={dberrortoggle}>
        <ModalHeader toggle={dberrortoggle}>Alert</ModalHeader>
        <ModalBody>
          <div style={{display:'flex',justifyContent:'center',width:'400px'}}>
            <img style={{width:'40px'}} src="/error.png"/>
            <p style={{marginTop:'20px',margin:'10px'}}>!Verification Failed</p>
            </div>
        </ModalBody>
        <ModalFooter>
          <Button color="primary" onClick={dberrortoggle}>
            OK
          </Button>
        </ModalFooter>
      </Modal>





</div>
  )
}
